language: go
go:
- 1.10.x
before_install:
- go get -t -v ./...
script:
- go test -race -coverprofile=coverage.out -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: NvWhL+ekKEiGp8lHu7RxplazS2kZdCqCs1vM1wxtSuyPXYyZMYNv9I/jlNk9GMOPZqgtQuiL8SsEvRpnNcexpo9KKNOTAOtjO3hGLSjDXK1kq3+e3/geIYluXYzao3S4bqpAhkbvTYmyriXsUe3ZhH1GQnOYHQS767BDmOLoueksagqEyLnSOZaivke9sPMFLbvy/rLDEzfc9/NUuDbcXk2A1N5Er9N4eY8WJ/RYUAV/ojK/Rw6tgw7THnYyn5fi1Adz6g+mWmCtuuYRcJnVBaoybvjIht+NkF6zm5sXOE77Wd+alZUyXGfCHvfHxH8d24CphRlaoE81wydshBd6yuAIGRdNVP7ybby8x8MV4VNGTcaORfCpSHj+OjKDDMkNPsNgRtopTacP1cz248lleotgKPmLY0405ctGDMKFn3CQ583Qh5nmcKmhmRUjXnMQNRkiASCtNUzjhea80vo9MhzyfNq+KIAjiEN8gBoFnIw5ri4TWuXzDU0kyKpZU2genXbE7XzfR4SJSnmoU3jbCIpeT+9DMRvDZaEQT4K2G6Wthyl3END5Fkp6sTF0z+GARcH5KTHCGbe1/pbWoWO7JDJQoD41u3xjMorN9T824QSv6G2VPrSUWGkM4HjPbV6Doo1WzTxmw6onZijNYcszPUbtjZW4j0C94Msu14+TEVQ=
  app: go-battlesnake
  on:
    repo: otonnesen/battlesnake-go
